spring:
  #数据源
  datasource:
    url: jdbc:mysql://121.5.165.86:3306/core?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 121.5.165.86
    port: 6379
    timeout: 30000
    database: 1


mybatis-plus:
  mapper-locations: classpath*:mapperxml/*.xml
logging:
  level:
    com.hj.mapper: debug


initSql: false
sqlPath: sql/sqldept

